#!/usr/bin/env bash
set -e

[ "$EUID" -eq 0 ] && print err "script cannot be run as root" ;

resourcedir="$HOME/.local/share/ronix"
configfile="$HOME/.config/ronix/config"
source "$configfile"
WINE="${WINEPATH}/bin/wine"
WINESERVER="${WINEPATH}/bin/wineserver"
WINEDLLPATH="${WINEPATH}/lib/x86_64-unix:${WINEPATH}/lib/x86_64-windows:${WINEPATH}/lib32/x86_64-unix:${WINEPATH}/lib32/x86_64-windows"
WINEARCH="win64"

print() {
  case $1 in
    info) echo "$(tput bold)[$(tput setaf 2)*$(tput sgr0)$(tput bold)]$(tput sgr0) $2" ;;
    err) echo "$(tput bold)[$(tput setaf 1)X$(tput sgr0)$(tput bold)]$(tput sgr0) $2" && exit 1;;
  esac
}


usage() {
	cat <<EOF
usage: ${0##*/} [OPTIONS]

Options:
-a                  launch Roblox app player wineprefix
-l                  list wineprefixes
-r [wineprefix]     delete a wineprefix
-c [wineprefix]     create a new wineprefix
-k [wineprefix]     kill wineprefix
-i [wineprefix]     install Roblox
EOF
}

wineprefix_init() {
  [ ! -d $resourcedir ] && print info "created resources directory" && mkdir -p "${resourcedir}"
	[ -d "${resourcedir}/$1" ] && print err "wineprefix $1 already exists"
	print info "creating wineprefix"
  mkdir "${resourcedir}/$1"
	WINEPREFIX="${resourcedir}/$1" $WINE wineboot 2>&1 || print err "wineprefix init fail"
	print info "wineprefix $1 created"
}


roblox_install() {
  [ ! -d $resourcedir ] && print info "created resources directory" && mkdir -p "${resourcedir}"
  [ ! -d $resourcedir/$1 ] && print err "wineprefix supplied does not exist"
  [ $resourcedir/$1 = $resourcedir ] && print err "wineprefix is invalid"
	[ ! -f "$WINE" ] && print err "wine binary does not exist"
	print info "installing Roblox into $1"
	print info "downloading Roblox client"
	curl -L https://www.roblox.com/download/client -o /tmp/rblx.exe || print err "roblox client download fail"
	print info "launching Roblox client"
	WINEPREFIX="${resourcedir}/$1" $WINE /tmp/rblx.exe || print err "roblox installation fail"
	WINEPREFIX="${resourcedir}/$1" $WINESERVER -k && print info "wineserver killed"
  print info "installing DXVK"
  local dxvk_ver=1.9.4
  curl -L https://github.com/doitsujin/dxvk/releases/download/v$dxvk_ver/dxvk-${dxvk_ver}.tar.gz | tar -xz -C /tmp
  PATH="$WINEPATH/bin:$PATH" WINEPREFIX="${resourcedir}/$1" /tmp/dxvk-$dxvk_ver/setup_dxvk.sh install
}

roblox_app(){
  exe="$(find ${resourcedir}/player -name RobloxPlayerBeta.exe -printf "%h/%f\n")"
  WINEPREFIX="${resourcedir}/player" $WINE "$exe" "--app"
}

main() {
  case "$1" in
    -a) roblox_app ;;
  	-l) find ${resourcedir} -maxdepth 1 -type d -printf "%f\n" | sed 1d ;;
    -r) rm -rfv ${resourcedir}/$2 ;;
  	-c) wineprefix_init "$2" ;;
    -k) WINEPREFIX="${resourcedir}/$2" wineserver -k ;;
    -i) roblox_install "$2" ;;
  	*)  usage  ;;
  esac
}

main "$@"
