#!/usr/bin/env bash
set -ex

[ ! "$EUID" -eq 0 ]

# WINEPATH=/home/wael/.local/share/grapejuice/user/wine-download/wine-tkg-staging-fsync-git-7.2.r0.g68441b1d
WINE=$WINEPATH/bin/wine
WINESERVER=$WINEPATH/bin/wineserver
WINEDLLPATH=$WINEPATH/lib/x86_64-unix:$WINEPATH/lib/x86_64-windows:$WINEPATH/lib32/x86_64-unix:$WINEPATH/lib32/x86_64-windows
WINEARCH="win64"

progname=${0##*/}
sharedir=${XDG_DATA_HOME:-$HOME/.local/share}
resourcedir=$sharedir/$progname
deskdir=$sharedir/applications

[ ! -d $resourcedir ] && mkdir -pv $resourcedir
[ ! -d $deskdir ] && mkdir -pv $deskdir
[ ! -f $deskdir/$progname.desktop ] && cat << EOF > $deskdir/$progname.desktop && xdg-mime default $progname.desktop x-scheme-handler/roblox-player
[Desktop Entry]
Type=Application
Name=Roblox App
Exec=$0 play %u
Categories=Game;
EOF
export WINEPREFIX=$resourcedir

idxvk() {
  local dxvkv=1.10.1
  curl -L https://github.com/doitsujin/dxvk/releases/download/v$dxvkv/dxvk-$dxvkv.tar.gz | tar -xz -C /tmp
  /tmp/dxvk-$dxvkv/setup_dxvk.sh install
  rm -rfv /tmp/dxvk-$dxvkv
}

groblox() {
  [ -z "$(find $resourcedir -name RobloxPlayerLauncher.exe)" ] && {
    curl -L https://www.roblox.com/download/client -o /tmp/rblx.exe
    $WINE /tmp/rblx.exe
    rm -rv /tmp/rblx.exe
    idxvk
  }
  exe=$(find $resourcedir -name RobloxPlayerLauncher.exe)
}

case $1 in
  play)
    shift
    groblox
    MANGOHUD=1 $WINE "$exe" $@
   ;;
  kill) $WINESERVER -k ;;
  dxvk) idxvk ;;
  del) rm -rfv $resourcedir ;;
esac

