#!/usr/bin/env bash
# if you see this, stuff went down
# Version
VERSION="b0.0.1"
# Colors
G='\033[0;32m'
NC='\033[0;0m'
B='\033[1m'
NB='\033[0m'
BL='\033[0;34m'
R='\033[0;31m'
O='\033[0;33m'
[ "$EUID" -eq 0 ] && echo "${R}${B}[ERR] ${NC}Running on root is not supported." && exit 1
LOGFOLDER="$HOME/.local/var/log/ronix"
ROOTFOLDER="$HOME/.local/share/ronix"
mkdir -p "$HOME/.local/share/ronix"
mkdir -p "$HOME/.local/var/log/ronix"
# Code from stackexchange
# This justs make a cool animated spinning |
spinner() {
    local i sp n
    sp='/-\|'
    n=${#sp}
    printf ' '
    while sleep 0.1; do
        printf "%s\b" "${sp:i++%n:1}"
    done
}

# Wineprefix creation command (STILL A PROTOTYPE, IT WILL BE EXTENDED WHEN CONFIG FILE SUPPORT IS ADDED)
wineprefix_init() {
	date=$(date +"%Y%m%d-%H-%M-%S")
	printf "${BL}${B}[I] ${NC}Log file is stored in $LOGFOLDER/wineprefix_init-$date\n" 2>&1 | tee -a "$LOGFOLDER/wineprefix_init-$date"; 
	if [ -d "$ROOTFOLDER/$1" ]; then
		printf "${R}${B}[E] ${NC}Wineprefix $1 already exists! Exiting...\n" 2>&1 | tee -a "$LOGFOLDER/wineprefix_init-$date" && exit 1; 
	fi
	printf "${BL}${B}[I] ${NC}Creating wineprefix $1 " 2>&1 | tee -a "$LOGFOLDER/wineprefix_init-$date"; 
	spinner &
	WINEPREFIX="$ROOTFOLDER/$1" wine wineboot 2>&1 | tee -a "$LOGFOLDER/wineprefix_init-$date" >/dev/null;
	kill "$!";
	case "$?" in
		0) ;;
		1) printf "${R}${B}[E] ${NC}Wine failed creating the wineprefix! Check the logfile for more information" 2>&1 | tee -a "$LOGFOLDER/wineprefix_init-$date" >/dev/null ;;
	esac
	printf "\n${BL}${B}[I] ${NC}Wineprefix $1 created! ($ROOTFOLDER/$1)\n" 2>&1 | tee -a "$LOGFOLDER/wineprefix_init-$date";
}

# Wineprefix list
wineprefix_list() {
	printf "${BL}${B}[I] ${NC}Available wineprefixes:\n${O}${B}"
	ls "$ROOTFOLDER"
}

case "$1" in
	--wineprefixes) wineprefix_list ;;
	--createwineprefix) wineprefix_init "${@:2}" ;;
esac
