#!/usr/bin/env -S sh -e
[ "$(id -u)" -eq 0 ] && echo 'please run as normal user' >&2 && exit 1

WINE="$WINEPATH/bin/wine"
WINESERVER="$WINEPATH/bin/wineserver"
PROGNAME="${0##*/}"
SHAREDIR="${XDG_DATA_HOME:-$HOME/.local/share}"
RESDIR="$SHAREDIR/$PROGNAME"
APPDIR="$SHAREDIR"/applications
APPFILE="$APPDIR/$PROGNAME.desktop"
ENVFILE="${XDG_CONFIG_HOME:-$HOME/.config}/$PROGNAME/env"

# shellcheck source=/dev/null
[ -f "$ENVFILE" ] && . "$ENVFILE"
[ ! -d "$RESDIR" ] && mkdir -pv "$RESDIR"
[ ! -d "$APPDIR" ] && mkdir -pv "$APPDIR"
[ ! -f "$APPFILE" ] && cat << EODESKTOPFILE > "$APPFILE" 
[Desktop Entry]
Type=Application
Name=Roblox App
Exec=$0 -p %u
Categories=Game;
EODESKTOPFILE
xdg-mime default "$PROGNAME".desktop x-scheme-handler/roblox-player
export WINEPREFIX="$RESDIR"

fpsunlocker_handler() {
	[ ! -f "$RESDIR"/rbxfpsunlocker.exe ] && \
		echo "[*] installing fpsunlocker"
		curl -L https://github.com/axstin/rbxfpsunlocker/releases/download/v4.4.2/rbxfpsunlocker-x64.zip | zcat > "$RESDIR"/rbxfpsunlocker.exe
	echo "[*] launching fpsunlocker"
	$WINE "$RESDIR"/rbxfpsunlocker.exe
}

dxvk_handler() {
	echo "[*] launching DXVK handler"
	curl -L https://github.com/doitsujin/dxvk/releases/download/v1.10.1/dxvk-1.10.1.tar.gz | tar -xz -C /tmp
	/tmp/dxvk-1.10.1/setup_dxvk.sh "$1" 
	rm -rfv /tmp/dxvk-1.10.1
}

get_roblox_directory() {
	echo "$RESDIR"/drive_c/Program\ Files\ \(x86\)/Roblox/Versions/version-*
}

install_roblox() {
	echo "[*] installing roblox"
	curl -L https://www.roblox.com/download/client -o /tmp/rblx.exe
	$WINE /tmp/rblx.exe
	rm -rfv /tmp/rblx.exe
}

launch_roblox() {
	echo "[*] launching roblox"
	[ -f "$(get_roblox_directory)"/RobloxPlayerLauncher.exe ] || install_roblox
	roblox_directory="$(get_roblox_directory)"
	[ -n "$RWSH_FFLAGS" ] && { 
		echo "[*] applying roblox fflags"
		csdir="$roblox_directory/ClientSettings"
		[ ! -d "$csdir" ] && mkdir -pv "$csdir"	
		echo "$RWSH_FFLAGS" > "$csdir"/ClientAppSettings.json
	}
	[ "$RWSH_FPSUNLOCKER_ENABLE" = true ] && fpsunlocker_handler &
	[ ! "$#" = 0 ] # error on 0 arguments
	$WINE "$roblox_directory/RobloxPlayerLauncher.exe" "$@"
}

# shellcheck disable=SC2034
case $1 in
	-p) shift; launch_roblox "$@" ;;
	-i) install_roblox ;;
	-k) $WINESERVER -k ;;
	-d) rm -rfv "$RESDIR" "$APPFILE" ;;
	-x) dxvk_handler "$2" ;;
	-f) fpsunlocker_handler ;;
	-h|--help|*)  
		cat <<-EOUSAGE
		usage: $PROGNAME [OPTION] [ARGS]

		OPTIONS
			-p <args>               launch roblox
			-i                      install roblox
			-k                      kill wineprefix
			-d                      remove all $PROGNAME files except configuration
			-x <install,uninstall>  DXVK handler 
			-f                      rbxfpsunlocker handler
			-h --help               display this page
		EOUSAGE
	;;
esac
